Arithmetic operations
anajekimova/-c-sharp-syllabus- pull request #2
Opened 2021-07-22 07:31 UTC by anajekimova

2021-07-22 19:04 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +           if (num1 == num || num2 == num)
te kkas nav ok ar spaciem

2021-07-22 19:05 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +                Console.WriteLine("It is  true!");
Ja atgriež vienu un to pašu, var likt zem viena if

2021-07-22 19:05 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise10/Program.cs
> +                else if (choice == 1)
šeit ir jābūt 2 un šis ir izlabots iekš codelex

2021-07-22 19:07 UTC, ausmoons requested changes

2021-07-22 19:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise10/Program.cs
> +        public static void calculateCircleArea()
Metodes ar lielo burtu

2021-07-22 19:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise10/Program.cs
> +            //todo
?

2021-07-22 19:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise10/Program.cs
> +            //todo
?

2021-07-22 19:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise2/Program.cs
> +            } else
else jaunā rindā

2021-07-22 19:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise8/Program.cs
> +
Daudz tukšu rindu

2021-07-22 20:11 UTC, anajekimova commented
izlaboti 1, 2, 8 un 10 uzdevums.

2021-07-24 04:38 UTC, ausmoons approved these changes

2021-08-13 15:19 UTC, merged