Test
anajekimova/-c-sharp-syllabus- pull request #9
Opened 2021-08-30 12:01 UTC by anajekimova

2021-08-30 18:12 UTC, ausmoons requested changes

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +            if (input1 == num || input2 == num || sum == num || difference == num || difference1 == num)
Return uzreiz

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise2/Program.cs
> +            if (check == 0)
Return uzreiz

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise8/Program.cs
> +            static void Main(string[] args)
Izskatās, ka ir par daudz atstarpju

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise8/SavingsAccount.cs
> +
Te var atstāt 1 tukšu rindu

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/Tests/Classes.Exercise1.Tests/ProductTests.cs
> +        public void PrintProduct_MousePrice_MousePriceInfo()
Metode saucas PrintPrice. Un trūkst // Arrange // Act // Assert komentāru

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/Tests/Coll.FlightPlanner.Tests/UnitTest1.cs
> +        public void Chek_Travel_Test()
Metode_KoPadod_KoSagaida

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/Tests/Coll.PhoneBook.Tests/UnitTest1.cs
> +    public class UnitTest1
Testu klases nosaukums parasti atbilst testējamajai klasei

2021-08-30 18:12 UTC, ausmoons commented on csharp-basics/exercises/Tests/Coll.PhoneBook.Tests/UnitTest1.cs
> +        public void Number_GetNumber_ReturnGetNumber()
Pārskati un izlabo namingus visos failos

2021-09-02 17:38 UTC, ausmoons requested changes

2021-09-02 17:38 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +            if (input1 == num || input2 == num || sum == num || difference == num || difference1 == num)
Es domāju ->  return input1 == num || input2 == num || sum == num || difference == num || difference1 == num

2021-09-02 17:38 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise2/Program.cs
> +            if (check == 0)
return check == 0

2021-09-02 17:38 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account_BACKUP_529.cs
> +{
Iepriekšējie faili vai tad nav lieki? Un arī šis fails izskatās lieks

2021-09-02 17:38 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account_LOCAL_313.cs
> +            _money -= i;
Izkskatās, ka nav pareizi merge conflikts atrisināts, jo rāda _LOCAL_313.cs , t_BASE_313.cs ..

2021-09-02 17:48 UTC, anajekimova commented on csharp-basics/exercises/ClassesAndObjects/Account/Account_LOCAL_313.cs
> +            _money -= i;
Man vakar palidzēja atrisinat confliktu un visual code vairak man neradijas ne kads konflikts.

2021-09-04 08:59 UTC, ausmoons requested changes

2021-09-04 08:59 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account_BACKUP_529.cs
> +{
Vēl joprojām ir lieki faili

2021-09-06 17:55 UTC, ausmoons requested changes

2021-09-06 17:55 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +
Lieka tukša rinda

2021-09-06 17:55 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program_BACKUP_1584.cs
> +<<<<<<< HEAD
Lieks fails

2021-09-06 17:55 UTC, ausmoons commented on csharp-basics/exercises/Tests/Arith.Exercise10.Tests/UnitTest1.cs
> +        {
Kas ir šis?

2021-09-06 17:55 UTC, ausmoons commented on csharp-basics/exercises/Tests/Exercise 1/UnitTest1.cs
> +        {
?

2021-09-07 17:54 UTC, ausmoons requested changes

2021-09-07 17:54 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise5/Date_BACKUP_326.cs
> +using System.Collections.Generic;
Tev vēl ir lieki faili. Pārskati visu

2021-09-07 19:02 UTC, ausmoons requested changes

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise2/Program.cs
> +            //..
Lieki komentāri

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Collections/ListExercise7/Program.cs
> +            //        }
Pārskati visus failus un izņem liekos komentārus

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Tests/Arith.Exercise10.Tests/UnitTest1.cs
> +        {
.

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Tests/Arith.Exercise7.Tests/UnitTest1.cs
> +        public void Gravivety_Numbers_ExpectGravity()
CalculatedGravety_KoPadod (kas ir tas 0 un 10?_ExpectGravity

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Tests/Arith.Exercise8.Tests/UnitTest1.cs
> +        public void MaxHoursWorked_Inputs_ExpectHourLimit()
CheckHours_HourseOverLimit_ExpectHourLimitMessage .. kaut kā tā

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Tests/Coll.WordCount/UnitTest1.cs
> +        public void Test1()
?

2021-09-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/Tests/TestUzdevumi/Program.cs
> +        static void Main(string[] args)
?

2021-09-08 14:58 UTC, anajekimova commented on csharp-basics/exercises/Collections/ListExercise7/Program.cs
> +            //        }
Ja apskatit collection branchu, visas lieki komentari ir nodzesti. Es nezinu kā sheit iznaaca, ka vini nav izlaboti.

2021-09-08 18:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/ListExercise7/Program.cs
> +            //        }
Tu ar so PR pārrakstīsi to, kas ir main. Iemergo šeit collection branchu un atstāj to, ko tev vajag

2021-09-12 20:55 UTC, anajekimova commented on csharp-basics/exercises/Collections/ListExercise7/Program.cs
> +            //        }
Sveika. Kad tev bus laiks, apskatit test uzdevumu. tagad man liekas jabut pareizi.

2021-09-13 19:05 UTC, EdgarsSalmins commented on csharp-basics/exercises/Collections/ListExercise7/Program.cs
> +            //        }
te viss b'us k'artiba.. es tikko paskat'ijos.. nevajadzētu būt situācijai ka kko pārraksta. ;)

2021-09-19 17:28 UTC, ausmoons approved these changes

2021-09-20 16:19 UTC, merged